version: 2.1
jobs:
  build:
    working_directory: ~/mock-server-build
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
